name: 'VTH module scraper'
description: 'Upsert a vth module from scraped info'
inputs:
  version:
    description: 'The version number to set in the helm values'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Scrape"
      shell: bash
      working-directory: ${{ github.action_path }}
      run: ./dist/$(echo "${{runner.os}}" | tr "[:upper:]" "[:lower:]")
      env:
        INPUT_VERSION: ${{ inputs.version }}