name: 'VTH module scraper'
description: 'Upsert a vth module from scraped info'
inputs:
  version:
    description: 'The version number to set in the helm values'
    required: true
runs:
  using: composite
  steps:
    - name: Download Go modules
      shell: bash
      run: go mod download
      working-directory: ${{ github.action_path }}

    - name: Build go project
      shell: bash
      run: go build
      working-directory: ${{ github.action_path }}
#      env:
#        INPUT_VERSION: ${{ inputs.version }}