name: 'VTH module scraper'
description: 'Upsert a vth module from scraped info'
inputs:
  version:
    description: 'The version number to set in the helm values'
    required: true
runs:
  using: composite
  steps:
    - name: "Scrape"
      shell: bash
      working-directory: ${{ github.action_path }}
      run: go run main.go
      env:
        INPUT_VERSION: ${{ inputs.version }}