// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/domain/module/api/v1/model.proto

package module_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Spark with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Spark) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Spark with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SparkMultiError, or nil if none found.
func (m *Spark) ValidateAll() error {
	return m.validate(true)
}

func (m *Spark) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Readme

	// no validation rules for InputSchema

	if utf8.RuneCountInString(m.GetLabel()) < 1 {
		err := SparkValidationError{
			field:  "Label",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := SparkValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Icon

	if len(errors) > 0 {
		return SparkMultiError(errors)
	}

	return nil
}

// SparkMultiError is an error wrapping multiple validation errors returned by
// Spark.ValidateAll() if the designated constraints aren't met.
type SparkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SparkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SparkMultiError) AllErrors() []error { return m }

// SparkValidationError is the validation error returned by Spark.Validate if
// the designated constraints aren't met.
type SparkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SparkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SparkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SparkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SparkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SparkValidationError) ErrorName() string { return "SparkValidationError" }

// Error satisfies the builtin error interface
func (e SparkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpark.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SparkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SparkValidationError{}

// Validate checks the field values on DetailEntity with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DetailEntity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DetailEntity with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DetailEntityMultiError, or
// nil if none found.
func (m *DetailEntity) ValidateAll() error {
	return m.validate(true)
}

func (m *DetailEntity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Repo

	// no validation rules for Version

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DetailEntityValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DetailEntityValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DetailEntityValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DetailEntityValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DetailEntityValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DetailEntityValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AggregateVersion

	// no validation rules for Readme

	// no validation rules for Label

	// no validation rules for Description

	// no validation rules for Icon

	for idx, item := range m.GetSparks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DetailEntityValidationError{
						field:  fmt.Sprintf("Sparks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DetailEntityValidationError{
						field:  fmt.Sprintf("Sparks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DetailEntityValidationError{
					field:  fmt.Sprintf("Sparks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DetailEntityMultiError(errors)
	}

	return nil
}

// DetailEntityMultiError is an error wrapping multiple validation errors
// returned by DetailEntity.ValidateAll() if the designated constraints aren't met.
type DetailEntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DetailEntityMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DetailEntityMultiError) AllErrors() []error { return m }

// DetailEntityValidationError is the validation error returned by
// DetailEntity.Validate if the designated constraints aren't met.
type DetailEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DetailEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DetailEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DetailEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DetailEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DetailEntityValidationError) ErrorName() string { return "DetailEntityValidationError" }

// Error satisfies the builtin error interface
func (e DetailEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDetailEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DetailEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DetailEntityValidationError{}

// Validate checks the field values on MasterEntity with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MasterEntity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MasterEntity with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MasterEntityMultiError, or
// nil if none found.
func (m *MasterEntity) ValidateAll() error {
	return m.validate(true)
}

func (m *MasterEntity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Repo

	// no validation rules for Version

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MasterEntityValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MasterEntityValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MasterEntityValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MasterEntityValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MasterEntityValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MasterEntityValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AggregateVersion

	// no validation rules for Label

	// no validation rules for Description

	// no validation rules for Icon

	// no validation rules for Sparks

	if len(errors) > 0 {
		return MasterEntityMultiError(errors)
	}

	return nil
}

// MasterEntityMultiError is an error wrapping multiple validation errors
// returned by MasterEntity.ValidateAll() if the designated constraints aren't met.
type MasterEntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MasterEntityMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MasterEntityMultiError) AllErrors() []error { return m }

// MasterEntityValidationError is the validation error returned by
// MasterEntity.Validate if the designated constraints aren't met.
type MasterEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MasterEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MasterEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MasterEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MasterEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MasterEntityValidationError) ErrorName() string { return "MasterEntityValidationError" }

// Error satisfies the builtin error interface
func (e MasterEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMasterEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MasterEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MasterEntityValidationError{}
